// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using mini_spotify.DAL;
using System;

namespace mini_spotify.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("mini_spotify.DAL.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa5ab627-3b64-4c22-9cc3-cca5fd57c896"),
                            Duration = 5,
                            Genre = "Classic",
                            Name = "Titanic",
                            Path = "."
                        },
                        new
                        {
                            Id = new Guid("1e072a96-8e09-4cd1-8834-b2326cf3062e"),
                            Duration = 4,
                            Genre = "Rap",
                            Name = "Low(feat. T-Pain",
                            Path = "."
                        });
                });

            modelBuilder.Entity("mini_spotify.DAL.Entities.Stream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("mini_spotify.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa5ab627-3b64-5d22-8cc3-cca5fd57c896"),
                            Email = "s1140207@student.windesheim.nl",
                            FirstName = "Ronald",
                            LastName = "Haan",
                            PassWord = "z0baP7W/1IjRaZu91Ik5KbxhjvPgdaN5mo0rOOYvQ81/Ybfe",
                            UserName = "1140207"
                        },
                        new
                        {
                            Id = new Guid("aa5ab653-3b62-5e22-5cc3-cca5fd57c846"),
                            Email = "s1121300@student.windesheim.nl",
                            FirstName = "Ali",
                            LastName = "Alkhalil",
                            PassWord = "Z4BYDHHzYvaD4zo/OVv9yQats/+uVV6HdFp8xvvz1Ip4Dt+i",
                            UserName = "1121300"
                        },
                        new
                        {
                            Id = new Guid("45f3ddef-5288-47b5-832c-e03c92008c32"),
                            Email = "Test@user.com",
                            FirstName = "test",
                            LastName = "User",
                            PassWord = "abPnBhX0g3hVVOvTyQADucwZv1DgaPzXZ8MSib2wpC7dzYvM",
                            UserName = "testuser"
                        });
                });

            modelBuilder.Entity("mini_spotify.DAL.Entities.Stream", b =>
                {
                    b.HasOne("mini_spotify.DAL.Entities.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId");

                    b.Navigation("Song");
                });
#pragma warning restore 612, 618
        }
    }
}
