// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mini_spotify.DAL;

namespace mini_spotify.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("mini_spotify.DAL.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa5ab627-3b64-4c22-9cc3-cca5fd57c896"),
                            Duration = 5,
                            Genre = "Classic",
                            Name = "Titanic",
                            Path = "."
                        },
                        new
                        {
                            Id = new Guid("52f5aab5-e89e-497c-94a9-01b2961e5f27"),
                            Duration = 4,
                            Genre = "Rap",
                            Name = "Low(feat. T-Pain",
                            Path = "."
                        });
                });

            modelBuilder.Entity("mini_spotify.DAL.Entities.Stream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("mini_spotify.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa5ab627-3b64-5d22-8cc3-cca5fd57c896"),
                            Email = "s1140207@student.windesheim.nl",
                            FirstName = "Ronald",
                            LastName = "Haan",
                            PassWord = "tA1EvGT0VPo6QDf+dPQmyyEv/KD5WaXaz721lSIAgImosSUv",
                            UserName = "1140207"
                        },
                        new
                        {
                            Id = new Guid("aa5ab653-3b62-5e22-5cc3-cca5fd57c846"),
                            Email = "s1121300@student.windesheim.nl",
                            FirstName = "Ali",
                            LastName = "Alkhalil",
                            PassWord = "xDpX3fbWOO4pkXV0FcNJMVhiyo3z83XdjWajl1FgGtl3Em7r",
                            UserName = "1121300"
                        });
                });

            modelBuilder.Entity("mini_spotify.DAL.Entities.Stream", b =>
                {
                    b.HasOne("mini_spotify.DAL.Entities.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId");

                    b.Navigation("Song");
                });
#pragma warning restore 612, 618
        }
    }
}
